name: Node CI

on:
  push:
    branches:
    - master
    - devaradhanm/*
  pull_request:

jobs:
  build:
    name: first build job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{ secrets.GITHUB_TOKEN}}     
        
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
      
    - name: install dependencies
      run: yarn install
    
#     - name: Upload reports
#       uses: actions/upload-artifact@v1.0.0
#       with:
#        # Artifact name
#        name: reports
#        # Directory containing files to upload
#        path: ${{ github.workspace }}/packages/cli/src/scanner/reports
    
#     - name: check formatting
#       run: yarn format-check
      
#     - name: check copyright on files
#       run: yarn copyright-check
    
#     - name: clean
#       run: yarn clean
    
    - name: build
      run: yarn build -- -- --env.version=$BUILD_NUMBER
    
#     - name: run linter
#       run: yarn lint
    
    - name: test
      run: yarn test --ci --coverage
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    
    - name: Codecov
      run: yarn publish-code-coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
